INSERT INTO [AnalyticsBootcampDB].[dbo].[AppsStageEnhanced]
SELECT apps.[AppName]
      ,apps.[AppFancyName]
      ,apps.[CompanyName]
      ,apps.[Purchases]
      ,apps.[Ads]
      ,apps.[SharesInfo]
      ,apps.[SharesLocation]
      ,apps.[UnrestrictedInternet]
      ,apps.[UsersInteract]
      ,apps.[AgeRating]
      ,apps.[ParentalGuidance]
      ,apps.[Downloads]
      ,apps.[Category]
      ,apps.[LowPrice]
      ,apps.[TopPrice]
      ,apps.[Price]
      ,apps.[PaidApp]
      ,apps.[Rating]
      ,apps.[RatingCount]
      ,apps.[Installs]
      ,apps.[MinimumInstalls]
      ,apps.[MaximumInstalls]
      ,apps.[Free]
      ,apps.[ReleaseDate]
      ,apps.[LastUpdated]
      ,apps.[EditorsChoice]
      ,apps.[DaysOnMarket]
      ,apps.[ReleaseYear]
      ,apps.[RelativeDownloadsPerformance]
	  ,CASE WHEN companies.[GamesCount] > 1 THEN 1 ELSE 0 END AS [CompanyIsExperienced]
	  ,companies.[GamesCount]
  FROM [AnalyticsBootcampDB].[dbo].[AppsStage] apps
  LEFT JOIN [AnalyticsBootcampDB].[dbo].[CompaniesStage] companies on apps.CompanyName = companies.CompanyName